spring:
  application:
    name: eval-system
  profiles:
    active: develop,default
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: enabled
      logic-delete-value: 0
      logic-not-delete-value: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info
